//! Pinned SHA-256 digests for the native runtime archives Koharu downloads
//! (llama.cpp, ZLUDA, CUDA wheels) before loading code from them.
//!
//! The list lives in `koharu-runtime/checksums.txt` (`sha256sum` format, keyed
//! by download URL) and is generated by `scripts/runtime-checksums.ts`. After
//! bumping a pinned version, re-run that script; the tests below fail until
//! every URL the code can download is listed.

use std::io::Read;
use std::path::Path;

use anyhow::{Context, Result, anyhow, bail};
use sha2::{Digest, Sha256};

const CHECKSUMS: &str = include_str!("../checksums.txt");

/// `(sha256_hex, url)` for every non-comment line.
fn entries() -> impl Iterator<Item = (&'static str, &'static str)> {
    CHECKSUMS
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .filter_map(|line| line.split_once(char::is_whitespace))
        .map(|(hash, url)| (hash, url.trim()))
}

/// The pinned digest for `url`, or an error if it isn't pinned. Downloads
/// without a pinned digest are refused rather than trusted.
pub(crate) fn expected_sha256(url: &str) -> Result<&'static str> {
    entries()
        .find(|(_, pinned)| *pinned == url)
        .map(|(hash, _)| hash)
        .ok_or_else(|| {
            anyhow!(
                "no pinned SHA-256 for `{url}`; run `bun scripts/runtime-checksums.ts` \
                 to update koharu-runtime/checksums.txt"
            )
        })
}

#[cfg(test)]
pub(crate) fn pinned_urls() -> impl Iterator<Item = &'static str> {
    entries().map(|(_, url)| url)
}

/// Hex SHA-256 of the file at `path`.
pub(crate) fn sha256_file(path: &Path) -> Result<String> {
    let mut file = std::fs::File::open(path)
        .with_context(|| format!("failed to open `{}`", path.display()))?;
    let mut hasher = Sha256::new();
    let mut buf = vec![0u8; 1024 * 1024];
    loop {
        let n = file
            .read(&mut buf)
            .with_context(|| format!("failed to read `{}`", path.display()))?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    Ok(hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect())
}

/// Fails unless the file at `path` hashes to `expected`.
pub(crate) fn verify_file(path: &Path, expected: &str) -> Result<()> {
    let actual = sha256_file(path)?;
    if !actual.eq_ignore_ascii_case(expected) {
        bail!(
            "checksum mismatch for `{}`: expected {expected}, got {actual}; \
             the download may be corrupted or tampered with",
            path.display()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::io::Write;

    use super::*;

    #[test]
    fn checksums_file_is_well_formed() {
        let mut count = 0;
        for (hash, url) in entries() {
            assert_eq!(hash.len(), 64, "bad digest length for {url}");
            assert!(
                hash.chars().all(|c| c.is_ascii_hexdigit()),
                "bad digest for {url}"
            );
            assert!(url.starts_with("https://"), "non-https url {url}");
            count += 1;
        }
        assert!(count > 0, "checksums.txt has no entries");
    }

    #[test]
    fn unpinned_url_is_refused() {
        let err = expected_sha256("https://example.com/evil.zip").unwrap_err();
        assert!(err.to_string().contains("no pinned SHA-256"));
    }

    #[test]
    fn verify_file_accepts_match_and_rejects_mismatch() {
        let mut file = tempfile::NamedTempFile::new().unwrap();
        file.write_all(b"abc").unwrap();
        // SHA-256("abc")
        let abc = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad";
        assert_eq!(sha256_file(file.path()).unwrap(), abc);
        verify_file(file.path(), abc).unwrap();
        verify_file(file.path(), &abc.to_uppercase()).unwrap();

        let err = verify_file(file.path(), &"0".repeat(64)).unwrap_err();
        assert!(err.to_string().contains("checksum mismatch"));
    }
}
