// @ts-nocheck
/**
 * Regenerates koharu-runtime/checksums.txt: the pinned SHA-256 of every native
 * runtime archive Koharu downloads on first launch. koharu-runtime refuses any
 * download (or cached copy) that isn't listed here with a matching digest.
 *
 * Versions are read from the Rust sources, so after bumping one of them just
 * re-run this script:
 *   - llama.cpp release assets for LLAMA_CPP_TAG   (.cargo/config.toml)
 *   - ZLUDA release assets for RELEASE_TAG         (koharu-runtime/src/zluda.rs)
 *   - CUDA wheels listed in WHEELS                 (koharu-runtime/src/cuda.rs)
 *
 * Digests come from GitHub's release API (`asset.digest`, falling back to
 * hashing the download) and PyPI's JSON API.
 *
 * Usage:
 *   bun scripts/runtime-checksums.ts          # rewrite checksums.txt
 *   bun scripts/runtime-checksums.ts --check  # exit 1 if it is out of date
 * Set GITHUB_TOKEN to avoid GitHub API rate limits.
 */
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const root = path.resolve(__dirname, '..')
const outputPath = path.join(root, 'koharu-runtime', 'checksums.txt')

const LLAMA_REPO = 'ggml-org/llama.cpp'
const ZLUDA_REPO = 'vosen/ZLUDA'

async function read(relative: string): Promise<string> {
  return readFile(path.join(root, relative), 'utf8')
}

function capture(source: string, pattern: RegExp, what: string): string {
  const match = source.match(pattern)
  if (!match) throw new Error(`could not find ${what}`)
  return match[1]
}

async function fetchJson(url: string, headers: Record<string, string> = {}) {
  const res = await fetch(url, { headers })
  if (!res.ok) throw new Error(`GET ${url} failed: ${res.status} ${await res.text()}`)
  return res.json()
}

async function sha256OfUrl(url: string): Promise<string> {
  const res = await fetch(url)
  if (!res.ok || !res.body) throw new Error(`GET ${url} failed: ${res.status}`)
  const hasher = new Bun.CryptoHasher('sha256')
  for await (const chunk of res.body) hasher.update(chunk)
  return hasher.digest('hex')
}

async function githubRelease(repo: string, tag: string): Promise<string[]> {
  const headers: Record<string, string> = { Accept: 'application/vnd.github+json' }
  if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`
  const release = await fetchJson(
    `https://api.github.com/repos/${repo}/releases/tags/${encodeURIComponent(tag)}`,
    headers,
  )
  const lines: string[] = []
  for (const asset of release.assets.sort((a, b) => a.name.localeCompare(b.name))) {
    // Built the same way as the Rust download URLs (RELEASE_BASE_URL/tag/name).
    const url = `https://github.com/${repo}/releases/download/${tag}/${asset.name}`
    const digest = asset.digest?.startsWith('sha256:')
      ? asset.digest.slice('sha256:'.length)
      : await sha256OfUrl(url)
    lines.push(`${digest}  ${url}`)
  }
  return lines
}

async function pypiWheels(pkg: string, version: string): Promise<string[]> {
  const release = await fetchJson(`https://pypi.org/pypi/${pkg}/${version}/json`)
  return release.urls
    .filter((file) => file.filename.endsWith('.whl'))
    .sort((a, b) => a.filename.localeCompare(b.filename))
    .map((file) => `${file.digests.sha256}  ${file.url}`)
}

async function generate(): Promise<string> {
  const llamaTag = capture(
    await read('.cargo/config.toml'),
    /LLAMA_CPP_TAG\s*=\s*"([^"]+)"/,
    'LLAMA_CPP_TAG in .cargo/config.toml',
  )
  const zludaTag = capture(
    await read('koharu-runtime/src/zluda.rs'),
    /const RELEASE_TAG: &str = "([^"]+)"/,
    'RELEASE_TAG in koharu-runtime/src/zluda.rs',
  )
  const wheels = [
    ...(await read('koharu-runtime/src/cuda.rs')).matchAll(/package: "([^"/]+)\/([^"]+)"/g),
  ].map(([, pkg, version]) => ({ pkg, version }))
  if (wheels.length === 0) throw new Error('no WHEELS found in koharu-runtime/src/cuda.rs')

  const sections: string[] = [
    '# Generated by scripts/runtime-checksums.ts. Do not edit by hand; re-run the script.',
    '# SHA-256 of every native runtime archive Koharu downloads, keyed by download URL.',
    '# koharu-runtime verifies each download (and each cached copy) against this list.',
    '',
    `# llama.cpp ${llamaTag}`,
    ...(await githubRelease(LLAMA_REPO, llamaTag)),
    '',
    `# ZLUDA ${zludaTag}`,
    ...(await githubRelease(ZLUDA_REPO, zludaTag)),
  ]
  for (const { pkg, version } of wheels) {
    sections.push('', `# ${pkg} ${version} (PyPI)`, ...(await pypiWheels(pkg, version)))
  }
  return sections.join('\n') + '\n'
}

async function main() {
  const check = process.argv.includes('--check')
  const expected = await generate()
  const current = await readFile(outputPath, 'utf8').catch(() => '')

  if (current === expected) {
    console.log('koharu-runtime/checksums.txt is up to date')
    return
  }
  if (check) {
    console.error('koharu-runtime/checksums.txt is out of date. Expected contents:\n')
    console.error(expected)
    console.error('Run `bun scripts/runtime-checksums.ts` and commit the result.')
    process.exit(1)
  }
  await writeFile(outputPath, expected)
  console.log('wrote koharu-runtime/checksums.txt')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
