/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { OfficialPageMatch } from './officialPageMatch'
import type { PageId } from './pageId'

export interface AddOfficialPagesResponse {
  matched: OfficialPageMatch[]
  /**
   * Pages whose cleaned image took the release's onomatopoeia; their
   * rendered image was dropped and needs rendering again.
   */
  rerender: PageId[]
  /** Pages no file clearly matched (different size or picture). */
  unmatchedPages: PageId[]
  /** Files that matched no page or could not be read. */
  unusedFiles: string[]
}
