/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface AddOfficialPagesRequest {
  /** Image files of the official release (any order, extra pages fine). */
  paths: string[]
}
