/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DataConfig } from './dataConfig'
import type { HttpConfig } from './httpConfig'
import type { McpConfig } from './mcpConfig'
import type { PipelineConfig } from './pipelineConfig'
import type { ProviderConfig } from './providerConfig'
import type { TelemetryConfig } from './telemetryConfig'

export interface AppConfig {
  data?: DataConfig
  http?: HttpConfig
  mcp?: McpConfig
  pipeline?: PipelineConfig
  providers?: ProviderConfig[]
  telemetry?: TelemetryConfig
}
