/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { BootstrapState } from './bootstrapState'

export interface BootstrapStatus {
  /**
   * Why the last attempt failed; set when `state` is `failed`.
   * @nullable
   */
  error?: string | null
  state: BootstrapState
}
