/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { BootstrapState } from './bootstrapState'

export interface BootstrapStatus {
  /**
   * Why the last attempt failed; set when `state` is `failed`.
   * @nullable
   */
  error?: string | null
  state: BootstrapState
}
