/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type BootstrapState = (typeof BootstrapState)[keyof typeof BootstrapState]

export const BootstrapState = {
  starting: 'starting',
  ready: 'ready',
  failed: 'failed',
} as const
