/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { SkippedProject } from './skippedProject'

export interface CleanUpStorageResponse {
  /**
   * Files that could not be removed.
   * @minimum 0
   */
  failed: number
  /**
   * Space all projects take on disk, after the clean-up when applied.
   * @minimum 0
   */
  projectsBytes: number
  /** Projects left alone, with the reason. */
  skipped: SkippedProject[]
  /** @minimum 0 */
  thumbnailBytes: number
  /**
   * Thumbnails (made again when shown): removed, or removable.
   * @minimum 0
   */
  thumbnails: number
  /** @minimum 0 */
  unusedImageBytes: number
  /**
   * Old images no closed project refers to: removed, or removable.
   * @minimum 0
   */
  unusedImages: number
}
