/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface ClearProjectCacheResponse {
  /** @minimum 0 */
  bytesFreed: number
  /** @minimum 0 */
  filesRemoved: number
  /** @minimum 0 */
  filesSkipped: number
}
