/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */

export interface CodexDeviceLogin {
  /** @minimum 0 */
  intervalSeconds: number
  loginId: string
  /** @minimum 0 */
  timeoutSeconds: number
  userCode: string
  verificationUrl: string
}
