/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */

export type DownloadStatus =
  | {
      status: 'started'
    }
  | {
      status: 'downloading'
    }
  | {
      status: 'completed'
    }
  | {
      reason: string
      status: 'failed'
    }
