/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

/**
 * Patch for the editor/UI preferences blob. `client` is an opaque JSON
 * object string owned by the frontend; the backend stores it verbatim.
 */
export interface EditorConfigPatch {
  /** @nullable */
  client?: string | null
}
