/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

/**
 * Persisted editor / UI preferences.
 *
 * `client` is an opaque JSON document owned entirely by the frontend
 * (shortcuts, brush, favorite fonts, prompts, pipeline toggles, LLM
 * selection, render defaults, locale, theme, …). The backend stores and
 * echoes it verbatim — it never interprets the contents.
 *
 * This exists because the desktop webview loads the UI from the ephemeral
 * `http://127.0.0.1:<port>` origin, and browser `localStorage` is keyed by
 * that origin: when the port drifts (e.g. 4000 is busy at launch) every
 * persisted preference is silently wiped. Round-tripping prefs through
 * `config.toml` makes them survive restarts regardless of the port.
 *
 * Stored as a JSON *string* rather than a structured table because TOML has
 * no null value (a structured blob with absent/optional fields would break
 * serialization) and the blob's shape is the frontend's concern, not ours.
 */
export interface EditorConfig {
  /**
   * Frontend-owned preferences, serialized as a JSON object string.
   * Empty string means "no preferences saved yet".
   */
  client?: string
}
