/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */

/**
 * Axis of a two-colour fill gradient, in the text's local (unrotated) frame.
 */
export type GradientDirection = (typeof GradientDirection)[keyof typeof GradientDirection]

export const GradientDirection = {
  horizontal: 'horizontal',
  vertical: 'vertical',
} as const
