/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */

export interface HttpConfigPatch {
  /**
   * @minimum 0
   * @nullable
   */
  connectTimeout?: number | null
  /**
   * @minimum 0
   * @nullable
   */
  maxRetries?: number | null
  /**
   * @minimum 0
   * @nullable
   */
  readTimeout?: number | null
}
