/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */

export interface HttpConfig {
  /** @minimum 0 */
  connect_timeout?: number
  /** @minimum 0 */
  max_retries?: number
  /** @minimum 0 */
  read_timeout?: number
}
