/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */

export type ImageRole = (typeof ImageRole)[keyof typeof ImageRole]

export const ImageRole = {
  source: 'source',
  inpainted: 'inpainted',
  rendered: 'rendered',
  custom: 'custom',
} as const
