/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */
import type { LlmTarget } from './llmTarget'

export interface LlmCatalogModel {
  languages: string[]
  name: string
  target: LlmTarget
}
