/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */

export type MaskRole = (typeof MaskRole)[keyof typeof MaskRole]

export const MaskRole = {
  brushInpaint: 'brushInpaint',
  segment: 'segment',
  bubble: 'bubble',
} as const
