/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

/**
 * The MCP server at `/mcp`, through which AI assistants can drive Koharu.
 * Checked per request, so a change applies immediately.
 */
export interface McpConfig {
  enabled?: boolean
}
