/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

/**
 * The MCP server at `/mcp`, through which AI assistants can drive Koharu.
Checked per request, so a change applies immediately.
 */
export interface McpConfig {
  enabled?: boolean
}
