/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { PageId } from './pageId'

export interface OfficialPageMatch {
  /** File name of the release page it got. */
  file: string
  page: PageId
}
