/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface PipelineConfigPatch {
  /** @nullable */
  bubbleSegmenter?: string | null
  /** @nullable */
  detector?: string | null
  /**
   * @minimum 0
   * @nullable
   */
  flux2Steps?: number | null
  /** @nullable */
  flux2Strength?: number | null
  /** @nullable */
  fontDetector?: string | null
  /** @nullable */
  inpainter?: string | null
  /** @nullable */
  ocr?: string | null
  /** @nullable */
  renderer?: string | null
  /** @nullable */
  segmenter?: string | null
  /** @nullable */
  translator?: string | null
}
