/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */
import type { BlobRef } from './blobRef'
import type { NodeId } from './nodeId'

export interface PutMaskResponse {
  blob: BlobRef
  node: NodeId
}
