/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */
import type { ProjectMeta } from './projectMeta'
import type { ScenePages } from './scenePages'

export interface Scene {
  /** Pages in insertion order; `IndexMap` ordering *is* the page order. */
  pages: ScenePages
  project: ProjectMeta
}
