/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface SkippedProject {
  id: string
  /** `open` (open here or in another window), or why it can't be read. */
  reason: string
}
