/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface StartPipelineResponse {
  operationId: string
  /**
   * Pages the run covers. With `onlyMissing`, `0` means every page in the
   * scope was already done (the run finishes at once).
   * @minimum 0
   */
  pageCount: number
}
