/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { NodeId } from './nodeId'
import type { PageId } from './pageId'
import type { ReadingOrder } from './readingOrder'
import type { Region } from './region'
import type { TextAlign } from './textAlign'
import type { TextShaderEffect } from './textShaderEffect'
import type { TextStrokeStyle } from './textStrokeStyle'

export interface StartPipelineRequest {
  /**
   * Pixels to inset text from each edge of its layout box, to stop glyphs
   * and strokes being clipped at the box border.
   * @nullable
   */
  boxPadding?: number | null
  /** @nullable */
  defaultFont?: string | null
  /**
   * Global render defaults applied when a text node has no explicit
   * per-node override. The renderer falls back to auto-fit / predicted
   * values when these are absent.
   * @nullable
   */
  defaultFontSize?: number | null
  /**
   * `None` → whole project, `Some(pages)` → just those pages.
   * @nullable
   */
  pages?: PageId[] | null
  readingOrder?: null | ReadingOrder
  region?: null | Region
  shaderEffect?: null | TextShaderEffect
  shaderStroke?: null | TextStrokeStyle
  /**
   * Language of the source text, as an OCR hint (e.g. "Korean").
   * `None` = OCR model auto-detect.
   * @nullable
   */
  sourceLanguage?: string | null
  /** Engine ids (`inventory::submit!` ids) to run in order. */
  steps: string[]
  /** @nullable */
  systemPrompt?: string | null
  /** @nullable */
  targetLanguage?: string | null
  textAlign?: null | TextAlign
  /**
   * Optional text-node ids for engines that can operate on individual blocks.
   * @nullable
   */
  textNodeIds?: NodeId[] | null
}
