/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

/**
 * Crash reporting. Read once at launch (see [`crash_reports_enabled`]), so
a change takes effect after a restart.
 */
export interface TelemetryConfig {
  /** Send crash reports and app-health sessions to the Koharu developers
  (Sentry). Only official builds carry a Sentry DSN. */
  crash_reports?: boolean
}
