/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface TextStrokeStyle {
  /**
   * Explicit outline colour. `None` = automatic: contrast against the
   * resolved text colour (white text gets a black outline and vice
   * versa). Became `Option` in scene format v5; earlier formats stored a
   * required colour that defaulted to white, converted on upgrade in
   * `session.rs::compat`.
   * @nullable
   * @items.minimum 0
   */
  color?: number[] | null
  enabled?: boolean
  /** @nullable */
  widthPx?: number | null
}
