/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

/**
 * Character-level overrides for a slice of translated text. Each optional
 * field inherits the block's [`TextStyle`] when absent; explicit booleans let
 * a range turn bold/italic off even when the whole block enables it.
 */
export interface TextRangeStyle {
  /** @nullable */
  bold?: boolean | null
  /**
   * @nullable
   * @items.minimum 0
   */
  color?: number[] | null
  /** @nullable */
  italic?: boolean | null
}
