/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */

/**
 * Reading axis of a text block.
 */
export type TextDirection = (typeof TextDirection)[keyof typeof TextDirection]

export const TextDirection = {
  horizontal: 'horizontal',
  vertical: 'vertical',
} as const
