/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */
import type { GradientDirection } from './gradientDirection'

/**
 * Two-colour gradient across the text fill. The fill starts at
 * `TextStyle::color` and ends at `to`; the stroke keeps its own colour.
 */
export interface TextFillGradient {
  direction: GradientDirection
  /** @items.minimum 0 */
  to: number[]
}
