/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 */
import type { BlobRef } from './blobRef'
import type { FontPrediction } from './fontPrediction'
import type { TextDirection } from './textDirection'
import type { TextStyle } from './textStyle'
import type { Transform } from './transform'

export interface TextData {
  confidence?: number
  /** @nullable */
  detectedFontSizePx?: number | null
  /** @nullable */
  detector?: string | null
  fontPrediction?: null | FontPrediction
  /** @nullable */
  linePolygons?: number[][][] | null
  lockLayoutBox?: boolean
  renderedDirection?: null | TextDirection
  /**
   * Font size the renderer actually used for the last sprite (auto-fit
   * result or explicit override). Lets the UI scale text with box resizes.
   * @nullable
   */
  renderedFontSizePx?: number | null
  /** @nullable */
  rotationDeg?: number | null
  sourceDirection?: null | TextDirection
  /** @nullable */
  sourceLang?: string | null
  sprite?: null | BlobRef
  spriteTransform?: null | Transform
  style?: null | TextStyle
  /** @nullable */
  text?: string | null
  /** @nullable */
  translation?: string | null
}
