/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { TextRangeStyle } from './textRangeStyle'

/**
 * A half-open UTF-8 byte range (`start..end`) in `TextData::translation`.
 * Ranges may overlap; later entries win per property. Producers should keep
 * them sorted, non-empty, and on character boundaries.
 */
export interface TextStyleRange {
  /** @minimum 0 */
  end: number
  /** @minimum 0 */
  start: number
  style: TextRangeStyle
}
